FROM node:18

ENV NODE_ENV development
ENV PORT 3000
ENV HOST 0.0.0.0

WORKDIR /usr/src/app

COPY ["./package.json", "./package-lock.json*", "./"]
RUN npm i

COPY . .

CMD ["sh", "-c", "npm run dev -- --port $PORT --host $HOST"]
