version: "3.4"

services:
  frontend:
    # image: frontend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
  backend:
    build: "backend"
    restart: always
    environment:
      spring.datasource.url : "jdbc:postgresql://postgresql:5432/postgres"
      server.port: 8000
    ports:
      - 8000:8000
  postgresql:
    image: "postgres:13"
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
