@startuml
rectangle users


hexagon platform {
    rectangle organisations
}

rectangle product
rectangle copy
rectangle borrowing

users -r-> organisations :  MSG: UserCreated


product   --> organisations : Authorization
copy      --> organisations : Authorization
borrowing --> organisations : Authorization

product -> copy      : MSG : ProductCreated
copy    -> borrowing : MSG : CopyCreated


@enduml