name: Java CI with Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    paths: 
      - backend/**

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: List files in the repository
      working-directory: ./backend
      run: |
         ${{ github.workspace }}/backend/gradlew test
