name: Frontend CI - prettier

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    paths: 
      - frontend/**

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Run Prettier Check
      run: npm run prettier:check