name: Frontend CI - prettier

on:
  push:
    paths:
      - frontend/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Run Prettier Check
      run: npm run prettier:check